name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10, verflixt

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master # don't get confused by @master - it is the version of the checkout action. You repo will be checked out with ${{ github.ref }}
      - name: Build site and deploy maven registry
        env:
            GITHUB_USERNAME: x-access-token
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BINTRAY_BAOPSO_API_KEY : ${{ secrets.BINTRAY_BAOPSO_API_KEY }}
        run: mvn --no-transfer-progress --settings .github/maven-settings.xml clean site deploy
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: target/site